### ISSUE TITLE
Feature Request: Create and name animations/layers in one step

### ISSUE THREAD

**Issue by kwhitley** [haremlife/AnimationPoser#4]
### The Problem
Currently, a user has to hit "add animation", then rename it (from say, "Animation#1), then hit "add animation" again... in order to name it.  This is counterintuitive.

### A Solution
If the user has filled out the name box, "add animation"/layer should use that name when creating the animation/layer, thus saving those extra fumbly steps.

**Comment by haremlife** [comment]
Hey! Thanks for reporting. This is now fixed. You click "Add Animation", then rename it. No need to hit "add animation" again.
